# Generated by Django 2.2.1 on 2019-05-15 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='from_user',
        ),
    ]
