# Generated by Django 2.2.1 on 2019-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='deadline',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
